# Plugin developed by GFelberg 
# Config.yml		        

# language: en
# Thanks for downloading my plugin. For more plugins, dont forget to look my updates!
# If you find any bugs or ideas to the plugin, pm me at spigot.

# language: br/pt
# Obrigado por baixar meu plugin. Para mais plugins, não esqueça de olhar as atualizações!
# Se você achar qualquer erro ou ideia para o plugin, mande messagem no spigot.

# Permissions

# inventoryview.admin : Access to the players inventories and the Help Page
# inventoryview.bypass : Access to interact with the players inventories, as yours. It only works if the protection rules are being followed correctly.
# inventoryview.reload : Access to Reload the Plugin

# PlaceHolders

# %player_inv% : Gets the specified player chosen to open the inventory
# %player_echest% : Gets the specified player chosen to open the enderchest

# Update-Check Option - https://www.spigotmc.org/resources/inventoryview.75100/
# If true, a permission will be required to recieve the notifications if the player doesnt have the OP enabled
update-check: true

# Configuration 1.0
# This configuration will display the InventoryView Messages 
  
InventoryView:
  Prefix: '&a[&eInventoryView&a]&r' 
  PlayerNotFound: '&cThe player is offline!'
  
# Configuration 1.1
# This configuration will display the Help Page Messages

Help:
  Page: '&eShows this page'
  Invsee: '&eOpen the players inventories'
  Invechest: '&eOpen the players enderchests'
  Reload: '&eReloads the Plugin'
  
# Configuration 1.2
# This configuration will display the Player Inventory Messages

PlayerInventory:
  Message: '&b%player_inv% &eInventory Opened'
  Yourself: '&cYou cant open your own inventory!'
  
# Configuration 1.3
# This configuration will display the Player Enderchest Messages 
  
PlayerEnderchest:
  Message: '&b%player_echest% &eEnderchest Opened'
  Yourself: '&cYou cant open your own enderchest!'

# Configuration 1.4
# This configuration will display the   
  
# Configuration 1.5
# This configuration will disply the Inventory Protection Events

# Interact : If true, the player will not be able to interact with the players inventories, as yours. If the player has permission "inventoryview.bypass",
# the player will have access to interact with the players inventories, as yours.

# BlockAdmin : If true, no one will be able to interact with the players inventories, as yours, even with OP or the permission "inventoryview.bypass" activated.
# This option will only have effect if the 'Interact' option is "true".

InventoryProtection:
  Interact: true
  BlockAdmin: true  
  