name: InventoryView
version: 1.2
author: GFelberg
main: me.GFelberg.InventoryView.Main
commands:
  inventoryview:
    usage: /<command>
    aliases: [iv]
  invsee:
    usage: /<command>
  invechest:
    usage: /<command>